# Structurelint Configuration for Mass Code Platform (MCP)
# This enforces project structure, organization, and architectural integrity

root: true

# Exclude patterns - directories to skip during linting
exclude:
  - "**/bin/**"
  - "**/obj/**"
  - "**/node_modules/**"
  - "**/.git/**"
  - "**/packages/**"
  - "**/.vs/**"
  - "**/.vscode/**"

# Entry points for dead code detection (Phase 2)
# These are the starting points for analyzing which files are actually used
entrypoints:
  - "src/MCP.ApiGateway/Program.cs"
  - "src/MCP.RefactoringWorker/Program.cs"
  - "src/MCP.ValidationWorker/Program.cs"
  - "**/*Tests.cs"
  - "tests/**/*.cs"

# Architectural layers (Phase 1)
# Define clear dependency boundaries between components
layers:
  # MCP.Contracts - Pure interface definitions (no dependencies)
  - name: 'Contracts'
    path: 'src/MCP.Contracts/**'
    dependsOn: []

  # MCP.Core - Shared models and services
  - name: 'Core'
    path: 'src/MCP.Core/**'
    dependsOn: ['Contracts']

  # MCP.ApiGateway - REST API service
  - name: 'ApiGateway'
    path: 'src/MCP.ApiGateway/**'
    dependsOn: ['Contracts', 'Core']

  # MCP.RefactoringWorker - Roslyn transformation worker
  - name: 'RefactoringWorker'
    path: 'src/MCP.RefactoringWorker/**'
    dependsOn: ['Contracts', 'Core']

  # MCP.ValidationWorker - Validation service
  - name: 'ValidationWorker'
    path: 'src/MCP.ValidationWorker/**'
    dependsOn: ['Contracts', 'Core']

  # MCP.Plugins.* - Refactoring plugins (only depend on Contracts)
  - name: 'Plugins'
    path: 'src/MCP.Plugins.*/**'
    dependsOn: ['Contracts']

rules:
  # ====================================================================
  # Phase 0: Filesystem Structure Validation
  # ====================================================================

  # Limit directory nesting to prevent over-complicated structures
  max-depth:
    max: 7
    message: "Directory depth should not exceed 7 levels to maintain navigability"

  # Limit files per directory to improve organization
  max-files-in-dir:
    max: 25
    message: "Directories should contain no more than 25 files for better organization"

  # Limit subdirectories per directory
  max-subdirs:
    max: 15
    message: "Directories should not have more than 15 subdirectories"

  # Enforce naming conventions for files
  # Note: structurelint supports camelCase, PascalCase, kebab-case, snake_case
  naming-convention:
    # C# files should use PascalCase
    "**/*.cs": "PascalCase"
    # Project files should use PascalCase
    "**/*.csproj": "PascalCase"
    # Configuration files can use various cases
    "**/*.json": "camelCase|PascalCase|kebab-case"
    "**/*.yml": "kebab-case"
    "**/*.yaml": "kebab-case"

  # Disallow certain file patterns
  disallowed-patterns:
    - "*.tmp"
    - "*.bak"
    - "*.swp"
    - ".DS_Store"
    - "Thumbs.db"

  # Note: file-existence rule disabled to avoid requiring files in every directory
  # In .NET projects, only the root needs README, .sln, and .gitignore

  # ====================================================================
  # Phase 1: Architectural Layer Enforcement
  # ====================================================================

  # Enable layer boundary enforcement
  # This ensures that dependencies only flow in the allowed direction
  enforce-layer-boundaries: true

  # ====================================================================
  # Phase 2: Dead Code Detection
  # ====================================================================

  # Detect orphaned files (files not reachable from entry points)
  # Disabled for now as this is a new project with potential orphaned code
  disallow-orphaned-files: false

  # Detect unused exports (symbols that are exported but never imported)
  # Disabled for now during initial development
  disallow-unused-exports: false

  # ====================================================================
  # Phase 3: Test Validation
  # ====================================================================

  # Test adjacency validation
  # For C# projects, tests are typically in a separate tests/ directory
  # Disabled for now - tests exist but with different naming patterns (*Tests.cs)
  # test-adjacency:
  #   pattern: "separate"
  #   file-patterns:
  #     - "src/**/*.cs"
  #   exemptions:
  #     - "src/**/Program.cs"
  #     - "src/**/Startup.cs"
  #     - "**/*Controller.cs"

  # Test location validation
  test-location:
    integration-test-dir: "tests"
    allow-adjacent: false          # C# convention: tests in separate directory
    file-patterns:
      - "**/*Tests.cs"
      - "tests/**/*.cs"
    exemptions:
      - "**/bin/**"
      - "**/obj/**"

# Overrides for specific file patterns
overrides:
  # Relaxed rules for test files
  - files: ['tests/**', '**/*Tests.cs']
    rules:
      max-files-in-dir: 50         # Test directories can have more files
      disallow-orphaned-files: 0   # Test files may not be "used" in traditional sense
      disallow-unused-exports: 0   # Test helpers may have unused exports
      naming-convention: 0         # Tests may use different naming patterns

  # Relaxed rules for documentation
  - files: ['docs/**', '**/*.md']
    rules:
      disallow-orphaned-files: 0
      disallow-unused-exports: 0
