# Structurelint Configuration for Mass Code Platform (MCP)
# This enforces project structure, organization, and architectural integrity
# All features enabled following best practices

root: true

# Exclude patterns - directories to skip during linting
exclude:
  - "**/bin/**"
  - "**/obj/**"
  - "**/node_modules/**"
  - "**/.git/**"
  - "**/packages/**"
  - "**/.vs/**"
  - "**/.vscode/**"

# Entry points for dead code detection (Phase 2)
# These are the starting points for analyzing which files are actually used
entrypoints:
  - "src/MCP.ApiGateway/Program.cs"
  - "src/MCP.RefactoringWorker/Program.cs"
  - "src/MCP.ValidationWorker/Program.cs"
  - "**/*Tests.cs"
  - "tests/**/*.cs"

# Architectural layers (Phase 1)
# Define clear dependency boundaries between components
layers:
  # MCP.Contracts - Pure interface definitions (no dependencies)
  - name: 'Contracts'
    path: 'src/MCP.Contracts/**'
    dependsOn: []

  # MCP.Core - Shared models and services
  - name: 'Core'
    path: 'src/MCP.Core/**'
    dependsOn: ['Contracts']

  # MCP.ApiGateway - REST API service
  - name: 'ApiGateway'
    path: 'src/MCP.ApiGateway/**'
    dependsOn: ['Contracts', 'Core']

  # MCP.RefactoringWorker - Roslyn transformation worker
  - name: 'RefactoringWorker'
    path: 'src/MCP.RefactoringWorker/**'
    dependsOn: ['Contracts', 'Core']

  # MCP.ValidationWorker - Validation service
  - name: 'ValidationWorker'
    path: 'src/MCP.ValidationWorker/**'
    dependsOn: ['Contracts', 'Core']

  # MCP.Plugins.* - Refactoring plugins (only depend on Contracts)
  - name: 'Plugins'
    path: 'src/MCP.Plugins.*/**'
    dependsOn: ['Contracts']

rules:
  # ====================================================================
  # Phase 0: Filesystem Structure Validation
  # ====================================================================

  # Limit directory nesting to prevent over-complicated structures
  max-depth:
    max: 7
    message: "Directory depth should not exceed 7 levels to maintain navigability"

  # Limit files per directory to improve organization
  max-files-in-dir:
    max: 25
    message: "Directories should contain no more than 25 files for better organization"

  # Limit subdirectories per directory
  max-subdirs:
    max: 15
    message: "Directories should not have more than 15 subdirectories"

  # Enforce naming conventions for files
  # Note: structurelint supports camelCase, PascalCase, kebab-case, snake_case
  naming-convention:
    # C# files should use PascalCase
    "**/*.cs": "PascalCase"
    # Project files should use PascalCase
    "**/*.csproj": "PascalCase"
    # Configuration files can use various cases
    "**/*.json": "camelCase|PascalCase|kebab-case"
    "**/*.yml": "kebab-case"
    "**/*.yaml": "kebab-case"
    # Markdown files
    "**/*.md": "UPPERCASE|PascalCase|kebab-case"

  # Disallow certain file patterns - prevent temporary and system files
  disallowed-patterns:
    - "*.tmp"
    - "*.bak"
    - "*.swp"
    - "*.orig"
    - ".DS_Store"
    - "Thumbs.db"
    - "desktop.ini"

  # Require README.md in key directories for documentation
  # Note: This rule applies to all directories. For C# projects, we've created
  # READMEs in major component directories (src/, tests/, docs/, each package)
  # Subdirectories like Models/, Services/, Controllers/ don't need READMEs
  #
  # Disabled at the rule level because structurelint doesn't support
  # directory-level filtering for file-existence checks.
  # Enable if you want strict documentation requirements:
  # file-existence:
  #   "README.md": "exists:1"

  # ====================================================================
  # Phase 1: Architectural Layer Enforcement
  # ====================================================================

  # Enable layer boundary enforcement
  # This ensures that dependencies only flow in the allowed direction
  # Plugins can only depend on Contracts, Workers can depend on Core+Contracts
  enforce-layer-boundaries: true

  # ====================================================================
  # Phase 2: Dead Code Detection
  # ====================================================================

  # Note: Dead code detection (orphaned files and unused exports) works
  # by analyzing import statements in source files. This is designed for
  # languages like Go, TypeScript, and JavaScript that use explicit imports.
  #
  # C# uses project references (.csproj) and namespace imports (using statements),
  # which structurelint doesn't currently parse. Therefore, these rules
  # produce false positives for C# projects where every file appears "orphaned."
  #
  # For C# dead code detection, use:
  # - Visual Studio Code Analysis
  # - ReSharper or Rider's "Find Unused Code"
  # - NDepend for architectural analysis
  #
  # Disabled for C# projects:
  # disallow-orphaned-files: true
  # disallow-unused-exports: true

  # ====================================================================
  # Phase 3: Test Validation
  # ====================================================================

  # Test location validation
  # Ensure tests are in the correct directory structure
  test-location:
    integration-test-dir: "tests"
    allow-adjacent: false          # C# convention: tests in separate directory
    file-patterns:
      - "**/*Tests.cs"
      - "tests/**/*.cs"
    exemptions:
      - "**/bin/**"
      - "**/obj/**"

  # ====================================================================
  # Phase 4: Code Quality Metrics
  # ====================================================================

  # Cognitive complexity (better than cyclomatic complexity)
  # Measures how difficult code is to understand
  max-cognitive-complexity:
    max: 15
    message: "Functions should not exceed cognitive complexity of 15"
    exemptions:
      - "**/*Tests.cs"      # Test methods can be more complex
      - "**/Program.cs"     # Entry points may have setup code

  # ====================================================================
  # Additional Best Practices
  # ====================================================================

  # Require directory naming conventions
  dir-naming-convention:
    "src/**": "PascalCase"
    "tests/**": "PascalCase"
    "docs/**": "PascalCase|kebab-case"

  # Prevent common anti-patterns
  disallow-deep-imports:
    max-depth: 3
    message: "Import paths should not be deeply nested (max 3 levels)"

# Overrides for specific file patterns
overrides:
  # Test directories - can have more files and complexity
  - files:
      - 'tests/**'
      - '**/Integration/**'
      - '**/*Tests.cs'
    rules:
      max-files-in-dir: 50
      max-cognitive-complexity: 30

  # Documentation - can have more files
  - files:
      - 'docs/**'
      - '**/*.md'
    rules:
      max-files-in-dir: 50

  # Configuration directories - can have more files
  - files:
      - '.github/**'
      - '**/.vscode/**'
    rules:
      max-files-in-dir: 50
